= Read Me

==  Requirements

* GNU `make`
* Docker
* `k3d` v5+ (v4 does not work with WSL)
* `kubectl`
* `helm` command line v2+ (https://helm.sh/)
* The `helm` plugin `diff` (https://github.com/databus23/helm-diff#using-helm-plugin-manager--23x)
* `helmfile` command line (https://helmfile.readthedocs.io/en/latest/)

* Build the Jenkins controller image with `make docker`
** If you want, you can upgrade re-generate the file `plugins.txt` file of this Docker image with `make plugins`

* Create a local cluster with `make cluster`
** If you want to use the local Docker image of the Jenkins controller, use the command `make docker-load` to add the image from your docker enginee into the cluster

* Deploy the Jenkins Controller with `make jenkins`

* Cleanup with one of these commands:
** Jenkins deploymenent: `make clean-jenkins`
** k3d cluster: `make clean-cluster`
** Everything: `make clean`


== Update Jenkins Plugins

The Docker image for the Jenkins controller uses a set of plugins defined with fixed versions in `docker/plugins.txt`.

If you want to update these plugins, execute the following script with Docker available: `./docker/update-plugins.sh`.

Please note that the script uses the Jenkins image version defined in `./docker/Dockerfile`.
